# Generated by Django 3.1.1 on 2020-09-09 17:37
import csv
import logging
import pathlib
import os

from django.db import migrations

from naics_scian.data import seed_database


log = logging.getLogger(__name__)
BASE_DIR = pathlib.Path(__file__).resolve().parent


def forward(apps, schema_editor):
    NAICSClassification = apps.get_model("naics_scian.table", "NAICSClassification")
    seed_database(Model=NAICSClassification)


def reverse(apps, schema_editor):
    NAICSClassification = apps.get_model("naics_scian.table", "NAICSClassification")
    NAICSClassification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [migrations.RunPython(forward, reverse)]
