# Generated by Django 3.1.1 on 2020-09-09 19:33
import pathlib

from django.db import migrations

from naics_scian.data import seed_database


BASE_DIR = pathlib.Path(__file__).resolve().parent


def forward(apps, schema_editor):
    NAICSClassification = apps.get_model(
        "naics_tables", "NAICSClassification"
    )
    seed_database(Model=NAICSClassification)


def reverse(apps, schema_editor):
    NAICSClassification = apps.get_model(
        "naics_tables", "NAICSClassification"
    )
    NAICSClassification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("naics_tables", "0001_initial"),
    ]

    operations = [migrations.RunPython(forward, reverse)]
